nodeLinker: node-modules

packageExtensions:
  puppeteer-extra-plugin-stealth@*:
    peerDependencies:
      puppeteer-extra: "*"
  puppeteer-extra-plugin-user-data-dir@*:
    peerDependencies:
      puppeteer-extra: "*"
  puppeteer-extra-plugin-user-preferences@*:
    peerDependencies:
      puppeteer-extra: "*"
  puppeteer-extra@*:
    peerDependencies:
      puppeteer-extra-plugin-stealth: "*"
      puppeteer-extra-plugin-user-data-dir: "*"
      puppeteer-extra-plugin-user-preferences: "*"

yarnPath: .yarn/releases/yarn-4.6.0.cjs
